pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=1'
    actions:
      queue:
        name: default
        method: squash
  - name: Automatic merge for hotfixes
    conditions:
      - label=hotfix
      - check-success=all
    actions:
      queue:
        name: hotfix
        method: squash
  - name: Automatic merge for Renovate PRs
    conditions:
      - author=renovate[bot]
      - check-success=all
    actions:
      queue:
        name: renovate
queue_rules:
  - name: default
    merge_conditions:
      - '#approved-reviews-by>=1'
  - name: hotfix
    conditions:
      - check-success=all
  - name: renovate
    conditions:
      - check-success=all
