ALTER TABLE user_profiles
RENAME COLUMN hasAcceptedTerms TO has_accepted_terms,
RENAME COLUMN hasCompletedProfile TO has_completed_profile,
RENAME COLUMN hasCreatedOrganization TO has_created_organization,
RENAME COLUMN isCreatedThroughOrgInvitation TO is_created_through_org_invitation;