CREATE TABLE "public"."team_members" (
  "id" bigint generated by DEFAULT AS identity NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT NOW(),
  "user_id" uuid NOT NULL REFERENCES "public"."user_profiles"("id") ON DELETE CASCADE,
  "role" project_team_member_role NOT NULL DEFAULT 'member'::project_team_member_role,
  "team_id" bigint NOT NULL
);

CREATE TABLE "public"."teams" (
  "id" bigint generated by DEFAULT AS identity NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT NOW(),
  "organization_id" uuid NOT NULL,
  "name" text NOT NULL
);

ALTER TABLE "public"."teams" enable ROW LEVEL SECURITY;