name: Sync v2 to v2-lemon

on:
  push:
    branches:
      - v2

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync v2 with v2-lemon
        run: |
          git checkout v2-lemon
          git merge v2
          git push origin v2-lemon